nonstop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('',include('products.urls'))
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('update_profile/',views.update_profile,name='update_profile'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
  <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">E-Comm</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'product_list' %}">Products</a>
        </li>

        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"  href="{% url 'users:logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'users:update_profile' %}">| Welcome <strong>{{request.user.username|title}}</strong> | </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'user_recommendations' id=request.user.pk %}">Recommendations</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"  href="{% url 'users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"  href="{% url 'users:login' %}">Login</a>
        </li>
        {%endif%}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"  href="{% url 'top_ten_list' %}"><em>Most Wanted!!</em></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"  href="{% url 'admin:index' %}">Admin</a>
        </li>

      </ul>

      <form class="d-flex" action="{% url 'search_products' %}">
        <input class="form-control me-2" type="search" name="q" placeholder="Enter Product ID" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
  </div>
    {% block content %}
    {%endblock%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>